baseurl = "http://rmn-web.net/"
languageCode = "ja-jp"
title = "まつゆき/rmn."

[[menu.main]]
  name = "プロフィール"
  url = "/page/profile"
  
[[menu.main]]
  name = "思い出"
  url = "/matsuhira"

[[menu.main]]
  name = "更新履歴"
  url = "/page/history"

[[menu.main]]
  name = "Twitterポリシー"
  url = "/page/twitter-policy"

[[menu.main]]
  name = "WWA Wing"
  url = "http://wwawing.com"

[params]
copyright = "2003-2015 Matsuyuki <a rel=\"license\" href=\"http://creativecommons.org/licenses/by/4.0/deed.ja\"><img alt=\"クリエイティブ・コモンズ・ライセンス\" style=\"border-width:0\" src=\"https://i.creativecommons.org/l/by/4.0/80x15.png\" /></a>"
