baseurl = "http://rmn-web.net/"
languageCode = "ja-jp"
title = "まつゆき/rmn."
copyright = "2003-2015 Matsuyuki ( CC BY License )"

[[menu.main]]
  name = "プロフィール"
  url = "/page/profile"
  
[[menu.main]]
  name = "思い出"
  url = "/matsuhira"

[[menu.main]]
  name = "更新履歴"
  url = "/page/history"

[[menu.main]]
  name = "Twitterポリシー"
  url = "/page/twitter-policy"

[[menu.main]]
  name = "WWA Wing"
  url = "http://wwawing.com"

