language: go
go:
- 1.5.1
env:
  global:
  - GIT_COMMITTER_NAME="Matsutanbot@Travis"
  - GIT_COMMITTER_EMAIL="matsuyuki.eca@gmail.com"
  - GIT_AUTHOR_NAME="Matsutanbot@Travis"
  - GIT_AUTHOR_EMAIL="matsuyuki.eca@gmail.com"
  - secure: Mv6kN5+KxxBW2nznGfJPlyhaHnahpCCMJR8FVwy6+rXtVJZI7lr/fZ/l0sHgAeIopSEfXW92xCK+Ylb36+ryU0JeNn77jtPdZ3Kz7Y/z4Jq6ZRPozPb278S5N0CVVgY65XEvwbpamglOYDpdiSatGL/yIzgBmZQVGBhAnkb4p+eeAe1QoueUdGP2Ia3J5Pzz5KsTBR3Y6AQASfG45DQ4yyO4b6TNUtfW64E8ivHwJmzrct7DGQmRBqvBFCjkmas04u+6RWl2tcQKnJJrGEAPs3PZ9UPJHuDyas3AsK7pXupql6vRt/Jc6EeIqF/bjqqmuVuw1V4L9XOWEHN3dp64DNedPy1R9uzJZq0qwfm7/287JAIaNdgl1JMlwGZtfuN9nPu9koKvaqR6P0jq8KxFtRF10HfAA5kF1hC4p4ukgaqB5538/fNZ+H1V2nV/U+lMQ2kaP3K1RKlw+BNqnm4FHBMQZRsA9e3JkRuKyIXEDd4+8VxywJDrTcTmARGY6BH1rZAkv1E4U9L3acx06we/vKIGFNMHm10bYkhTJ6eJXGcwPXA+qm24TOx4A0SEBlJLfAV4mD2meJHmIo8ty0LaKpPuzoXDE4oxQGX7z+aSjd3G5lolwMONWoGg4W+ectvfi9YBBuOjKge1zYH4fWLxGWwUS5uxcgm8HrkvbGJx40s=
install: go get -u -v github.com/spf13/hugo
script:
- git checkout -b gh-pages
- git rm -rf hugo/public
- git commit -m "temporal remove public"
- '[ $GH_TOKEN ] && git subtree add --prefix=hugo/public https://$GH_TOKEN@github.com/rmn31415/portfolio.rmn-web.net.git
  gh-pages --squash >& /dev/null'
- cd hugo
- echo -e "\033[0;32mDeploying updates to GitHub...\033[0m"
- hugo -t hugo-multi-bootswatch
- cd public
- git add -A
- msg="rebuilding site `date`"
- git commit -m "$msg" || echo "(nothing to commit)"
- cd ../..
- '[ $GH_TOKEN ] && git subtree push --prefix=hugo/public https://$GH_TOKEN@github.com/rmn31415/portfolio.rmn-web.net.git
  gh-pages >& /dev/null'
after_success:
- echo "OK"
