language: go

go:
  - 1.5.1

env:
  global:
    - GIT_COMMITTER_NAME="Matsutanbot@Travis"
    - GIT_COMMITTER_EMAIL="matsuyuki.eca@gmail.com"
    - GIT_AUTHOR_NAME="Matsutanbot@Travis"
    - GIT_AUTHOR_EMAIL="matsuyuki.eca@gmail.com"
    - secure: "ljn2DOZJs1L2ZtOna11VhRj2l1JC9jp9gge34bQwBhB716ZSFZzzwKU7HAI9HAO90fLkQq3TskJtLpusVPsZhjR1tMg++zyMU2HzBbhNdMH76IqigMhIDJh4/vPATRAne1KEwGkgMsg4R0qCv4/H79K70kNemt2kEYRkty2+UmsLZ+B+g6h8mwW5W08vQpvoh+8IeN/k07SRmIwgbyFOU0FTb8Fpqod63kdzLCQiXpfAxo5DgaPl5CWKW+7rp/bsoP5nnXdLAWwHDtNeKzAPJh9pUJx0i6lT7EMLfv/zw6fZHvYYKMPC+H884zRwixCOQ8+DKTlHjDldBK8j8cN3q7wAT25OKwWXIvdoSEEIYZhU3qOHbXD70i9xVA1sPzJuGpzIgYBMElQskjhTn/SNNOMzb3P5Rs57B8mw9oNmRZQ2plyXliX2Pq537bbk1W4BsEaFDZIgNt219PnAnWQtOezdnmqvp5qGsIjw8dXYEeu7HUjJ4xbqNZINPN5430tbkTUdyPp8TkABowpWpji5PbxWV5ta0UUC0+1AlZ5RS2ME18o4ybDmZEKEKUI8c22KHtE1fVIDvVdPeyDpZTE8m8zaJnVMU/VaM2Nz+J95L09L5LpL2EAOlX0nuene6R2d8HKRsDd2W+UPgIziUQmG+XDRv35BeZGbg532aQoEEbA="

install:
  go get -u -v github.com/spf13/hugo

script:
  - git checkout -b gh-pages
  - git branch -a
  - git rm -rf hugo/public
  - git commit -m "temporal remove public"
  - '[ $GH_TOKEN ] && git subtree add --prefix=hugo/public https://$GH_TOKEN@github.com/rmn31415/news.rmn-web.net.git gh-pages --squash'
  - cd hugo
  - echo -e "\033[0;32mDeploying updates to GitHub...\033[0m"
  - hugo -t hugo-multi-bootswatch
  - cd public
  - git add -A
  - msg="rebuilding site `date`"
  - git commit -m "$msg"
  - cd ../..
  - '[ $GH_TOKEN ] && git subtree push --prefix=hugo/public https://$GH_TOKEN@github.com/rmn31415/news.rmn-web.net.git gh-pages >& /dev/null'


after_success:
  - echo "OK"

